name: build

on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Setup poetry config
        run: python -m poetry config virtualenvs.create false
      - name: Install dependencies
        run: python -m poetry install
      - name: Format check
        run: black .
      - name: Flake8
        run: poetry run flake8 . --count --show-source --statistics
      - name: Lint with pylint
        run: pylint **/*.py
      - name: Test library
        run: poetry run pytest
